# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coder',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('code', models.CharField(max_length=300)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('is_outdate', models.BooleanField(default=False)),
                ('to_user', models.BooleanField(default=False)),
                ('permission', models.CharField(max_length=500)),
                ('extra_info', models.CharField(max_length=300, null=True, blank=True)),
                ('member', models.ForeignKey(to='account.Member')),
            ],
            options={
                'ordering': ['-create_time'],
                'verbose_name': '\u6388\u6743\u7801',
                'verbose_name_plural': '\u6388\u6743\u7801\u5217\u8868',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='ColletDate',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('user_type', models.CharField(max_length=20)),
                ('guarantee_type', models.CharField(max_length=20)),
                ('file_source_type', models.CharField(max_length=20)),
                ('analyst', models.CharField(default=b'', max_length=200)),
                ('up_time', models.DateTimeField(null=True, blank=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('id_num', models.CharField(max_length=50, null=True, blank=True)),
                ('cell', models.CharField(max_length=50, null=True, blank=True)),
                ('email', models.CharField(max_length=50, null=True, blank=True)),
                ('name', models.CharField(max_length=50, null=True, blank=True)),
                ('home_addr', models.CharField(max_length=200, null=True, blank=True)),
                ('home_tel', models.CharField(max_length=50, null=True, blank=True)),
                ('biz_addr', models.CharField(max_length=200, null=True, blank=True)),
                ('biz_tel', models.CharField(max_length=50, null=True, blank=True)),
                ('other_addr', models.CharField(max_length=200, null=True, blank=True)),
                ('bank_card1', models.CharField(max_length=20, null=True, blank=True)),
                ('bank_card2', models.CharField(max_length=20, null=True, blank=True)),
                ('flag1', models.CharField(max_length=50, null=True, blank=True)),
                ('flag2', models.CharField(max_length=50, null=True, blank=True)),
                ('flag', models.CharField(max_length=50, null=True, blank=True)),
                ('def_days', models.IntegerField(max_length=10, null=True, blank=True)),
                ('def_times', models.CharField(max_length=100, null=True, blank=True)),
                ('amount', models.CharField(max_length=50, null=True, blank=True)),
                ('notes', models.CharField(max_length=50, null=True, blank=True)),
                ('apply_date', models.CharField(max_length=50, null=True, blank=True)),
                ('observe_date', models.CharField(max_length=20, null=True, blank=True)),
                ('apply_channel', models.CharField(max_length=50, null=True, blank=True)),
                ('apply_id', models.CharField(max_length=100, null=True, blank=True)),
                ('apply_addr', models.CharField(max_length=200, null=True, blank=True)),
                ('apply_amount', models.IntegerField(max_length=24, null=True, blank=True)),
                ('apply_product', models.CharField(max_length=20, null=True, blank=True)),
                ('approval_status', models.CharField(max_length=50, null=True, blank=True)),
                ('approval_date', models.CharField(max_length=20, null=True, blank=True)),
                ('approval_amount', models.IntegerField(max_length=20, null=True, blank=True)),
                ('device_type', models.CharField(max_length=50, null=True, blank=True)),
                ('device_id', models.CharField(max_length=50, null=True, blank=True)),
                ('apply_type', models.CharField(max_length=50, null=True, blank=True)),
                ('type_vehicle_id', models.CharField(max_length=50, null=True, blank=True)),
                ('af_swift_number', models.CharField(max_length=50, null=True, blank=True)),
                ('custApiCode', models.CharField(max_length=50, null=True, blank=True)),
                ('envent', models.CharField(max_length=50, null=True, blank=True)),
                ('collateral', models.CharField(max_length=50, null=True, blank=True)),
                ('loan_date', models.CharField(max_length=20, null=True, blank=True)),
                ('loan_purpose', models.CharField(max_length=50, null=True, blank=True)),
                ('loan_status', models.CharField(max_length=50, null=True, blank=True)),
                ('repayment_periods', models.CharField(max_length=10, null=True, blank=True)),
                ('age', models.CharField(max_length=10, null=True, blank=True)),
                ('race', models.CharField(max_length=10, null=True, blank=True)),
                ('gender', models.CharField(max_length=10, null=True, blank=True)),
                ('birthday', models.CharField(max_length=20, null=True, blank=True)),
                ('marriage', models.CharField(max_length=20, null=True, blank=True)),
                ('edu', models.CharField(max_length=50, null=True, blank=True)),
                ('wechat_city', models.CharField(max_length=50, null=True, blank=True)),
                ('wechat_name', models.CharField(max_length=50, null=True, blank=True)),
                ('wechat_province', models.CharField(max_length=50, null=True, blank=True)),
                ('providentfund', models.CharField(max_length=20, null=True, blank=True)),
                ('socialsecurity', models.CharField(max_length=50, null=True, blank=True)),
                ('id_ps', models.CharField(max_length=50, null=True, blank=True)),
                ('id_start', models.CharField(max_length=20, null=True, blank=True)),
                ('id_end', models.CharField(max_length=20, null=True, blank=True)),
                ('id_city', models.CharField(max_length=30, null=True, blank=True)),
                ('id_type', models.CharField(max_length=30, null=True, blank=True)),
                ('civic_addr', models.CharField(max_length=200, null=True, blank=True)),
                ('civic_status', models.CharField(max_length=50, null=True, blank=True)),
                ('postalcode', models.CharField(max_length=14, null=True, blank=True)),
                ('city', models.CharField(max_length=50, null=True, blank=True)),
                ('province', models.CharField(max_length=50, null=True, blank=True)),
                ('contact_name_1', models.CharField(max_length=50, null=True, blank=True)),
                ('contact_relation_1', models.CharField(max_length=50, null=True, blank=True)),
                ('contact_cell_1', models.CharField(max_length=50, null=True, blank=True)),
                ('contact_name_2', models.CharField(max_length=50, null=True, blank=True)),
                ('contact_relation_2', models.CharField(max_length=50, null=True, blank=True)),
                ('contact_cell_2', models.CharField(max_length=50, null=True, blank=True)),
                ('contact_name_3', models.CharField(max_length=50, null=True, blank=True)),
                ('contact_relation_3', models.CharField(max_length=50, null=True, blank=True)),
                ('contact_cell_3', models.CharField(max_length=50, null=True, blank=True)),
                ('contact_name_4', models.CharField(max_length=50, null=True, blank=True)),
                ('contact_relation_4', models.CharField(max_length=50, null=True, blank=True)),
                ('contact_cell_4', models.CharField(max_length=50, null=True, blank=True)),
                ('contact_name_5', models.CharField(max_length=50, null=True, blank=True)),
                ('contact_relation_5', models.CharField(max_length=50, null=True, blank=True)),
                ('contact_cell_5', models.CharField(max_length=50, null=True, blank=True)),
                ('if_house', models.CharField(max_length=20, null=True, blank=True)),
                ('if_vehicle', models.CharField(max_length=20, null=True, blank=True)),
                ('housing_cate', models.CharField(max_length=50, null=True, blank=True)),
                ('vehicle_id', models.CharField(max_length=50, null=True, blank=True)),
                ('vehicle_type', models.CharField(max_length=50, null=True, blank=True)),
                ('biz_name', models.CharField(max_length=50, null=True, blank=True)),
                ('biz_size', models.CharField(max_length=50, null=True, blank=True)),
                ('industry', models.CharField(max_length=50, null=True, blank=True)),
                ('company_cate', models.CharField(max_length=50, null=True, blank=True)),
                ('salary', models.CharField(max_length=50, null=True, blank=True)),
                ('position', models.CharField(max_length=50, null=True, blank=True)),
                ('working_period', models.CharField(max_length=50, null=True, blank=True)),
                ('acc_open_date', models.CharField(max_length=20, null=True, blank=True)),
                ('card_level', models.CharField(max_length=15, null=True, blank=True)),
                ('branch', models.CharField(max_length=15, null=True, blank=True)),
                ('currency', models.CharField(max_length=15, null=True, blank=True)),
                ('ins_balance', models.CharField(max_length=24, null=True, blank=True)),
                ('update_balance', models.CharField(max_length=24, null=True, blank=True)),
                ('update_capital', models.CharField(max_length=24, null=True, blank=True)),
                ('update_date', models.CharField(max_length=20, null=True, blank=True)),
                ('update_interest', models.CharField(max_length=24, null=True, blank=True)),
                ('update_overduepayment', models.CharField(max_length=24, null=True, blank=True)),
                ('update_overlimitfee', models.CharField(max_length=24, null=True, blank=True)),
                ('update_servicefee', models.CharField(max_length=24, null=True, blank=True)),
                ('bill_day', models.CharField(max_length=20, null=True, blank=True)),
                ('bill_post', models.CharField(max_length=20, null=True, blank=True)),
                ('bill_addr', models.CharField(max_length=200, null=True, blank=True)),
                ('ins_amount', models.CharField(max_length=24, null=True, blank=True)),
                ('ins_date_claims', models.CharField(max_length=20, null=True, blank=True)),
                ('ins_firstlogindate', models.CharField(max_length=20, null=True, blank=True)),
                ('ins_newvehicleprice', models.CharField(max_length=24, null=True, blank=True)),
                ('ins_period', models.CharField(max_length=10, null=True, blank=True)),
                ('ins_yearly_claims_num', models.CharField(max_length=10, null=True, blank=True)),
                ('imei', models.CharField(max_length=50, null=True, blank=True)),
                ('imsi', models.CharField(max_length=50, null=True, blank=True)),
                ('mobil_type', models.CharField(max_length=50, null=True, blank=True)),
                ('gid', models.CharField(max_length=50, null=True, blank=True)),
                ('other_var1', models.CharField(max_length=50, null=True, blank=True)),
                ('var_exp1', models.CharField(max_length=200, null=True, blank=True)),
                ('other_var2', models.CharField(max_length=50, null=True, blank=True)),
                ('var_exp2', models.CharField(max_length=200, null=True, blank=True)),
                ('other_var3', models.CharField(max_length=50, null=True, blank=True)),
                ('var_exp3', models.CharField(max_length=200, null=True, blank=True)),
                ('other_var4', models.CharField(max_length=50, null=True, blank=True)),
                ('var_exp4', models.CharField(max_length=200, null=True, blank=True)),
                ('other_var5', models.CharField(max_length=50, null=True, blank=True)),
                ('var_exp5', models.CharField(max_length=200, null=True, blank=True)),
            ],
            options={
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Interface',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('name', models.CharField(max_length=100)),
                ('chinese_name', models.CharField(max_length=120)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('thread_num', models.IntegerField(default=10, verbose_name=b'\xe5\xb9\xb6\xe5\x8f\x91\xe6\x95\xb0')),
                ('max_map', models.IntegerField(default=0, verbose_name=b'\xe6\x9c\x80\xe5\xa4\xa7\xe5\x8c\xb9\xe9\x85\x8d\xe9\x87\x8f')),
            ],
            options={
                'ordering': ['-create_time'],
                'verbose_name': '\u63a5\u53e3\u540d\u79f0',
                'verbose_name_plural': '\u63a5\u53e3\u540d\u79f0\u5217\u8868',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='LineModel',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('line', models.CharField(max_length=800)),
                ('openid', models.IntegerField(max_length=14)),
                ('is_applyed', models.BooleanField(default=False)),
            ],
            options={
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='LogInfo',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('username', models.CharField(max_length=100, null=True, blank=True)),
                ('ip', models.CharField(max_length=30, null=True, blank=True)),
                ('filename', models.CharField(max_length=100, null=True, blank=True)),
                ('query_interface', models.CharField(max_length=500, null=True, blank=True)),
                ('num', models.IntegerField(null=True, blank=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-create_time'],
                'verbose_name': '\u65e5\u5fd7',
                'verbose_name_plural': '\u65e5\u5fd7',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='MappingedFile',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('file', models.FileField(max_length=500, upload_to=b'mappinged_file/%Y/%m')),
                ('file_size', models.IntegerField(max_length=4)),
                ('file_from', models.CharField(max_length=300, null=True)),
                ('is_cus_visible', models.BooleanField(default=True, verbose_name=b'\xe5\xae\xa2\xe6\x88\xb7\xe6\x98\xaf\xe5\x90\xa6\xe5\x8f\xaf\xe8\xa7\x81')),
                ('is_third_file', models.BooleanField(default=False, verbose_name=b'\xe6\x98\xaf\xe5\x90\xa6\xe4\xb8\xba\xe7\xac\xac\xe4\xb8\x89\xe6\x96\xb9\xe6\x96\x87\xe4\xbb\xb6')),
                ('is_csv', models.BooleanField(default=False, verbose_name=b'\xe6\x98\xaf\xe5\x90\xa6\xe4\xb8\xbacsv\xe6\x96\x87\xe4\xbb\xb6')),
                ('is_crypt', models.BooleanField(default=False)),
                ('id_num', models.IntegerField(max_length=4, null=True, blank=True)),
                ('cell_num', models.IntegerField(max_length=4, null=True, blank=True)),
                ('mail_num', models.CharField(max_length=40, null=True, blank=True)),
                ('password', models.CharField(max_length=50, null=True, blank=True)),
                ('is_haina', models.BooleanField(default=False, verbose_name=b'\xe6\x98\xaf\xe5\x90\xa6\xe7\x94\xbb\xe5\x83\x8f\xe6\x8e\xa5\xe5\x8f\xa3\xe5\x8c\xb9\xe9\x85\x8d')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('can_down', models.ManyToManyField(related_name=b'down_mappedfile', to='account.Member')),
                ('customer', models.ForeignKey(related_name=b'mappingedfile_customs', blank=True, to='account.Member', null=True)),
            ],
            options={
                'ordering': ['-create_time'],
                'verbose_name': 'Mapping\u8f93\u51fa\u6587\u4ef6',
                'verbose_name_plural': 'Mapping\u8f93\u51fa\u6587\u4ef6\u5217\u8868',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('name', models.CharField(max_length=100)),
                ('chinese_name', models.CharField(max_length=120)),
                ('head_status', models.BooleanField(default=False, verbose_name=b'\xe6\x98\xaf\xe5\x90\xa6\xe6\x9c\x89\xe8\xa1\xa8\xe5\xa4\xb4')),
                ('interface', models.CharField(max_length=50)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('max_map', models.IntegerField(max_length=10, null=True, blank=True)),
            ],
            options={
                'ordering': ['-create_time'],
                'verbose_name': '\u5957\u9910\u540d\u79f0',
                'verbose_name_plural': '\u5957\u9910\u540d\u79f0\u5217\u8868',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='MealHead',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('name', models.CharField(max_length=100)),
                ('head', models.CharField(max_length=100)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('meal', models.ForeignKey(to='analyse.Meal')),
            ],
            options={
                'ordering': ['-create_time'],
                'verbose_name': '\u5957\u9910\u8868\u5934\u5bf9\u7167',
                'verbose_name_plural': '\u5957\u9910\u8868\u5934\u5bf9\u7167\u5217\u8868',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='MealSort',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('name', models.CharField(max_length=100)),
                ('sort', models.CharField(max_length=500)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-create_time'],
                'verbose_name': '\u5957\u9910\u987a\u5e8f\u5bf9\u7167',
                'verbose_name_plural': '\u5957\u9910\u5957\u9910\u987a\u5e8f\u5217\u8868',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='PhoneFile',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('filename', models.FileField(upload_to=b'phone_file/%Y/%m')),
                ('file_from', models.CharField(max_length=100)),
                ('extra_info', models.CharField(max_length=300, null=True, blank=True)),
                ('total_lines', models.IntegerField(max_length=8, null=True, blank=True)),
                ('file_size', models.IntegerField(max_length=4, null=True, blank=True)),
                ('is_bingo', models.BooleanField(default=False)),
                ('applied_done_time', models.DateTimeField(null=True, blank=True)),
                ('task_id', models.IntegerField(max_length=8, null=True, blank=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(to='account.Member')),
            ],
            options={
                'ordering': ['-create_time'],
                'verbose_name': '\u53f7\u7801\u6587\u4ef6',
                'verbose_name_plural': '\u53f7\u7801\u6587\u4ef6\u5217\u8868',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='ReportFile',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('report_file', models.FileField(upload_to=b'report_file/%Y/%m')),
                ('file_desc', models.CharField(max_length=300, null=True, blank=True)),
                ('file_size', models.IntegerField(max_length=4)),
                ('passwd', models.CharField(max_length=10)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('can_down', models.ManyToManyField(related_name=b'down_reportfile', to='account.Member')),
                ('customer', models.ForeignKey(related_name=b'reportfile_customs', blank=True, to='account.Member', null=True)),
                ('mappinged_files', models.ManyToManyField(to='analyse.MappingedFile', null=True, blank=True)),
            ],
            options={
                'ordering': ['-create_time'],
                'verbose_name': '\u62a5\u544a\u6587\u4ef6',
                'verbose_name_plural': '\u62a5\u544a\u6587\u4ef6\u5217\u8868',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='SourceFile',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('file_source_type', models.CharField(blank=True, max_length=40, null=True, choices=[(b'', b'\xe8\xaf\xb7\xe9\x80\x89\xe6\x8b\xa9'), (b'BANK_CREDIT_CARD', b'\xe9\x93\xb6\xe8\xa1\x8c\xe4\xbf\xa1\xe7\x94\xa8\xe5\x8d\xa1'), (b'BANK_RETAIL', b'\xe9\x93\xb6\xe8\xa1\x8c\xe9\x9b\xb6\xe5\x94\xae'), (b'BANK_TO_PUBLIC', b'\xe9\x93\xb6\xe8\xa1\x8c\xe5\xaf\xb9\xe5\x85\xac'), (b'P2P_LOAN', b'P2P\xe5\x80\x9f\xe8\xb4\xb7'), (b'P2P_FINANCING', b'P2P\xe7\x90\x86\xe8\xb4\xa2'), (b'CONSUMER_FINANCE_COMPANY', b'\xe6\xb6\x88\xe8\xb4\xb9\xe9\x87\x91\xe8\x9e\x8d\xe5\x85\xac\xe5\x8f\xb8'), (b'SMALL_LOAN_AGENCY', b'\xe5\xb0\x8f\xe8\xb4\xb7\xe6\x9c\xba\xe6\x9e\x84'), (b'CAR_FINANCE', b'\xe6\xb1\xbd\xe8\xbd\xa6\xe9\x87\x91\xe8\x9e\x8d'), (b'GUARANTEE', b'\xe6\x8b\x85\xe4\xbf\x9d'), (b'INSURANCE', b'\xe4\xbf\x9d\xe9\x99\xa9'), (b'FILE_SOURCE_TYPES_OTHER', b'\xe5\x85\xb6\xe4\xbb\x96')])),
                ('guarantee_type', models.CharField(blank=True, max_length=40, null=True, choices=[(b'', b'\xe8\xaf\xb7\xe9\x80\x89\xe6\x8b\xa9'), (b'CREDIT_LOAD', b'\xe4\xbf\xa1\xe7\x94\xa8\xe8\xb4\xb7\xe6\xac\xbe'), (b'MORTGAGE_LOAN', b'\xe6\x8a\xb5\xe6\x8a\xbc\xe8\xb4\xb7\xe6\xac\xbe'), (b'BOTH', b'\xe5\x85\xbc\xe6\x9c\x89'), (b'GUARANTEE_TYPE_OTHER', b'\xe5\x85\xb6\xe4\xbb\x96')])),
                ('user_type', models.CharField(blank=True, max_length=40, null=True, choices=[(b'', b'\xe8\xaf\xb7\xe9\x80\x89\xe6\x8b\xa9'), (b'USUAL', b'\xe6\x99\xae\xe9\x80\x9a\xe4\xb8\xaa\xe4\xba\xba'), (b'WONER', b'\xe5\xb0\x8f\xe4\xb8\x9a\xe4\xb8\xbb'), (b'COMPANY', b'\xe4\xbc\x81\xe4\xb8\x9a'), (b'OTHER_USER', b'\xe5\x85\xb6\xe4\xbb\x96')])),
                ('filename', models.FileField(max_length=500, upload_to=b'source_file/%Y/%m')),
                ('file_from', models.CharField(max_length=100)),
                ('extra_info', models.CharField(max_length=300, null=True, blank=True)),
                ('is_done', models.BooleanField(default=False)),
                ('fields', models.CharField(max_length=1000, null=True, blank=True)),
                ('skip_lines', models.IntegerField(max_length=4, null=True, blank=True)),
                ('splitor', models.CharField(max_length=10, null=True, blank=True)),
                ('is_checked', models.BooleanField(default=False)),
                ('is_saved_db', models.BooleanField(default=False)),
                ('total_lines', models.IntegerField(max_length=8, null=True, blank=True)),
                ('file_size', models.IntegerField(max_length=4, null=True, blank=True)),
                ('id_num', models.IntegerField(max_length=4, null=True, blank=True)),
                ('is_sampling', models.BooleanField(default=False, verbose_name=b'\xe6\x98\xaf\xe5\x90\xa6\xe5\xb7\xb2\xe5\x8a\xa0\xe5\x85\xa5\xe6\x95\xb0\xe6\x8d\xae\xe9\x9b\x86\xe5\xb8\x82')),
                ('is_delete', models.BooleanField(default=False, verbose_name=b'\xe6\x98\xaf\xe5\x90\xa6\xe8\xa2\xab\xe5\x88\xa0\xe9\x99\xa4')),
                ('mail_num', models.IntegerField(max_length=4, null=True, blank=True)),
                ('is_applied', models.BooleanField(default=False)),
                ('applied_done_time', models.DateTimeField(null=True, blank=True)),
                ('is_has_new', models.BooleanField(default=False)),
                ('can_delete', models.BooleanField(default=False)),
                ('sampling_sort', models.CharField(max_length=20, null=True, verbose_name=b'\xe8\xaf\xa5\xe5\xae\xa2\xe6\x88\xb7\xe5\x9c\xa8\xe6\x95\xb0\xe6\x8d\xae\xe9\x9b\x86\xe5\xb8\x82\xe7\x9a\x84\xe6\x96\x87\xe4\xbb\xb6\xe4\xb8\xaa\xe6\x95\xb0', blank=True)),
                ('loan_amount', models.CharField(max_length=200, null=True, verbose_name=b'\xe8\xb4\xb7\xe6\xac\xbe\xe4\xba\xa7\xe5\x93\x81\xe9\xa2\x9d\xe5\xba\xa6', blank=True)),
                ('loan_deadline', models.CharField(max_length=200, null=True, verbose_name=b'\xe8\xb4\xb7\xe6\xac\xbe\xe4\xba\xa7\xe5\x93\x81\xe6\x9c\x9f\xe9\x99\x90', blank=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('can_down', models.ManyToManyField(related_name=b'down_sourcefile', to='account.Member')),
                ('custom', models.ForeignKey(to='account.Member')),
            ],
            options={
                'ordering': ['-create_time'],
                'verbose_name': '\u6e90\u6587\u4ef6',
                'verbose_name_plural': '\u6e90\u6587\u4ef6\u5217\u8868',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='ThirdMappedFile',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('is_distribute', models.BooleanField(default=False)),
                ('distribute_time', models.DateTimeField(null=True, blank=True)),
                ('fields', models.CharField(max_length=500)),
                ('skip_lines', models.IntegerField(max_length=4, null=True, blank=True)),
                ('splitor', models.CharField(max_length=10)),
                ('file', models.FileField(upload_to=b'thirdmapped_file/%Y/%m')),
                ('file_desc', models.CharField(max_length=200, null=True, blank=True)),
                ('file_size', models.IntegerField(max_length=4)),
                ('file_from', models.CharField(max_length=100, null=True, choices=[(b'MinHang', b'\xe6\xb0\x91\xe8\x88\xaa\xe4\xbf\xa1\xe6\x81\xaf'), (b'Bank_data', b'\xe9\x93\xb6\xe8\xa1\x8c\xe5\x8d\xa1\xe6\x95\xb0\xe6\x8d\xae'), (b'Account_change', b'\xe5\xb8\x90\xe6\x88\xb7\xe5\x8f\x98\xe5\x8a\xa8')])),
                ('trans_status', models.CharField(max_length=20, null=True, blank=True)),
                ('id_num', models.IntegerField(max_length=4, null=True, blank=True)),
                ('cell_num', models.IntegerField(max_length=4, null=True, blank=True)),
                ('mail_num', models.IntegerField(max_length=4, null=True, blank=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('can_down', models.ManyToManyField(related_name=b'down_thirdfile', to='account.Member')),
                ('source_file', models.ManyToManyField(to='analyse.SourceFile')),
                ('uploader', models.ForeignKey(to='account.Member')),
            ],
            options={
                'ordering': ['-create_time'],
                'verbose_name': '\u7b2c\u4e09\u65b9\u8f93\u51fa\u6587\u4ef6',
                'verbose_name_plural': '\u7b2c\u4e09\u65b9\u8f93\u51fa\u6587\u4ef6\u5217\u8868',
            },
            bases=(models.Model,),
        ),
        migrations.AddField(
            model_name='reportfile',
            name='source_file',
            field=models.ForeignKey(to='analyse.SourceFile', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='reportfile',
            name='uploader',
            field=models.ForeignKey(related_name=b'reportfile_uploaders', to='account.Member'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='mappingedfile',
            name='parent_file',
            field=models.ForeignKey(blank=True, to='analyse.ThirdMappedFile', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='mappingedfile',
            name='source_file',
            field=models.ForeignKey(to='analyse.SourceFile', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='mappingedfile',
            name='uploader',
            field=models.ForeignKey(related_name=b'mappingedfile_uploaders', blank=True, to='account.Member', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='linemodel',
            name='source_file',
            field=models.ForeignKey(to='analyse.SourceFile'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='colletdate',
            name='source_file',
            field=models.ForeignKey(to='analyse.SourceFile', null=True),
            preserve_default=True,
        ),
    ]
